apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: pwgen
  name: pwgen
  annotations:
    kubernetes.io/change-cause: "Upgrade to 1.7"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pwgen
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pwgen
        version: "1.7"
        type: web
    spec:
      containers:
      - image: boris/pwgen-web:1.7
        imagePullPolicy: IfNotPresent
        name: pwgen
        resources: {}
        ports:
        - containerPort: 5000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
