orbs:
  docker: circleci/docker@1.5.0
version: 2.1
workflows:
  build-and-publish-docker-image:
    jobs:
      - docker/publish:
          after_checkout:
            - run: 
              command: |
                export TAG=$(git rev-parse --short HEAD)
          image: boris/pwgen-web
          update-description: false
