version: 2
jobs:
  build:
    docker:
      - image: circleci/docker:3.8.1
        auth:
          username: boris
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - run: |
          TAG=$CIRCLE_BUILD_NUM
          docker build -t boris/pwgen-web:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push boris/pwgen-web:$TAG
