version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.1
        auth:
          username: boris
          password: $DOCKERHUB_PASSWORD
    environment:
      TAG: git rev-parse --short HEAD
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - run: |
          docker build -t boris/pwgen-web:$TAG .
