apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pwgen-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: pwgen.xyz
      http:
        paths:
          - path: /()(.*)
            pathType: Prefix
            backend:
              service:
                name: pwgen
                port:
                  number: 5000

